spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/trello_clone_prod}
    username: ${DB_USERNAME:tru123}
    password: ${DB_PASSWORD:tru12345}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
