export const ROUTE_NAMES = {
  home: "Home",
  login: "Login",
  register: "Register",
  stageList: "StageList",
  stageCreate: "StageCreate",
  stageDetail: "StageDetail",
  stageEdit: "StageEdit",
  projectDetail: "ProjectDetail",
  workspaceMembers: "WorkspaceMembers",
  workspaceSettings: "WorkspaceSettings",
  workspaceBoards: "WorkspaceBoards",
  workspaceCards: "WorkspaceCards",
  personalSettings: "PersonalSettings",
  personalActivity: "PersonalActivity",
  personalProfile: "PersonalProfile",
  trelloAccountProfile: "TrelloAccountProfile",
  accountSwitcher: "AccountSwitcher",
  adminDashboard: "admin-dashboard",
  adminUsers: "admin-users",
  adminUserDetail: "admin-user-detail",
  adminWorkspaces: "admin-workspaces",
  adminWorkspaceDetail: "admin-workspace-detail",
  adminBoards: "admin-boards",
  adminBoardDetail: "admin-board-detail",
  notFound: "NotFound",
} as const;

export const ROUTE_PATHS = {
  home: "/",
  login: "/auth/login",
  register: "/auth/register",
  stages: "/stages",
  stageCreate: "/stages/create",
  workspaceMembers: "/workspace/members",
  workspaceSettings: "/workspace/settings",
  workspaceBoards: "/workspace/boards",
  workspaceCards: "/workspace/cards",
  personalSettings: "/personal/settings",
  personalActivity: "/personal/activity",
  personalProfile: "/personal/profile",
  trelloAccountProfile: "/account/profile-display",
  accountSwitcher: "/account/switch",
  admin: "/admin",
} as const;
